name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: python -m unittest

    # Step 5: Build Docker image
    - name: Build Docker image
      run: sudo docker build -t benakiva/appsync_python:latest .

    # Step 6: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}


      

    # Step 7: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: sudo docker push benakiva/appsync_python
